/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:f4accb32-342a-4658-b681-570fd75f1e82",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_BpjotDADW",
    "aws_user_pools_web_client_id": "6iq8p0a131hh9uhfbtb94gsr7s",
    "oauth": {},
    "aws_user_files_s3_bucket": "thestore35d914010a624342bb7d7b776fdd3f57221623-dev",
    "aws_user_files_s3_bucket_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": "https://atlzkebcajdafcopeugo6fhdlq.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-xbij5rerjvdgzlte3fhwpzndra",
};


export default awsmobile;
